### ISSUE TITLE
Run into problems when @_socket is null.

### ISSUE THREAD

**Issue by jwalton** [benbria/node-lumberjack-protocol#6]
https://github.com/benbria/node-lumberjack-protocol/blob/master/src/Client.coffee#L100

Also elsewhere in this file.  Need to fix this.

**Comment by dule** [comment]
Yea, I think also [here](https://github.com/benbria/node-lumberjack-protocol/blob/49b4e465f3c7470c67d1856fbc85c7cd321cc394/src/Client.coffee#L137) it has also failed with the `_socket` being null.
