### ISSUE TITLE
`unref` property doesn't work properly

### ISSUE THREAD

**Issue by tuyakhov** [benbria/node-lumberjack-protocol#9]
In case i need to terminate an application after the Node.js event loop is empty. I am passing `unref: true` and process exits without waiting for socket connection and `_sendQueuedMessages()` to be processed.

**Comment by tuyakhov** [comment]
@jwalton Is it possible to make a release with that fix? I would be nice to see those changes in npm and be able to install them.

**Comment by jwalton** [comment]
Oops, sorry - published as v1.0.4.  Thanks again for the fix!
